"""Runtime configuration for the video localization application.

The configuration object deliberately contains no provider fallback settings.  A
missing credential or model identifier is handled by preflight instead of being
silently replaced with another service.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Mapping

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:  # pragma: no cover - dependency is declared in requirements
    load_dotenv = None

from utils.errors import ConfigurationError
from video_config import SEEDANCE_MAX_DURATION, SEEDANCE_TASK_TIMEOUT


FIXED_SEED_AUDIO_MODEL = "seed-audio-1.0"


def _text(env: Mapping[str, str], name: str, default: str = "") -> str:
    return str(env.get(name, default)).strip()


def _int(env: Mapping[str, str], name: str, default: int) -> int:
    value = _text(env, name, str(default))
    try:
        return int(value)
    except ValueError as exc:
        raise ConfigurationError(f"{name} must be an integer") from exc


def _float(env: Mapping[str, str], name: str, default: float) -> float:
    value = _text(env, name, str(default))
    try:
        return float(value)
    except ValueError as exc:
        raise ConfigurationError(f"{name} must be a number") from exc


def _path_from_env(env: Mapping[str, str], name: str, default: Path, base_dir: Path) -> Path:
    value = _text(env, name, str(default))
    path = Path(value).expanduser()
    return path if path.is_absolute() else base_dir / path


def _tool_from_env(
    env: Mapping[str, str],
    name: str,
    default: str,
    base_dir: Path,
    local_relative: str,
) -> str:
    """Prefer a bundled project tool while retaining PATH-based overrides."""

    value = _text(env, name, default)
    local_path = base_dir / local_relative
    if value == default and local_path.is_file():
        return str(local_path)
    path = Path(value).expanduser()
    if path.is_absolute():
        return str(path)
    if "/" in value or "\\" in value or value.startswith("."):
        return str((base_dir / path).resolve())
    return value


@dataclass(frozen=True)
class AppConfig:
    """Validated application settings.

    Secret values are hidden from the dataclass representation so accidental
    debug logging cannot print API keys.
    """

    ark_api_key: str = ""
    ark_base_url: str = "https://ark.cn-beijing.volces.com/api/v3"
    doubao_model: str = "doubao-seed-2-0-lite-260215"
    seedance_model_id: str = ""
    seedance_max_duration: int = SEEDANCE_MAX_DURATION
    seedance_task_timeout: int = SEEDANCE_TASK_TIMEOUT

    mediakit_api_key: str = ""
    seed_audio_api_key: str = ""
    seed_audio_endpoint: str = "https://openspeech.bytedance.com/api/v3/tts/create"
    seed_audio_model: str = FIXED_SEED_AUDIO_MODEL

    uguu_upload_url: str = "https://uguu.se/upload"
    uguu_max_file_mib: int = 128
    uguu_expire_hours: int = 3

    http_timeout: float = 180.0
    poll_interval: float = 10.0
    max_retries: int = 3
    work_dir: Path = Path("work")
    ffmpeg_bin: str = "ffmpeg"
    ffprobe_bin: str = "ffprobe"
    mediakit_cli_bin: str = "mediakit-cli"

    # Secret fields are still accessible to runtime adapters, but do not appear
    # in repr() generated by the dataclass.
    def __repr__(self) -> str:  # pragma: no cover - defensive secret hygiene
        return (
            "AppConfig("
            f"ark_base_url={self.ark_base_url!r}, "
            f"doubao_model={self.doubao_model!r}, "
            f"seedance_model_id={self.seedance_model_id!r}, "
            f"seedance_max_duration={self.seedance_max_duration!r}, "
            f"seedance_task_timeout={self.seedance_task_timeout!r}, "
            f"seed_audio_endpoint={self.seed_audio_endpoint!r}, "
            f"seed_audio_model={self.seed_audio_model!r}, "
            f"uguu_upload_url={self.uguu_upload_url!r}, "
            f"work_dir={str(self.work_dir)!r})"
        )

    @classmethod
    def from_env(
        cls,
        env: Mapping[str, str] | None = None,
        *,
        base_dir: Path | None = None,
        load_file: bool = True,
    ) -> "AppConfig":
        """Load the documented environment variables.

        ``env`` can be supplied by tests.  The real application loads a local
        ``.env`` file when python-dotenv is installed, while never requiring it
        to contain a secret or committing that file.
        """

        root = (base_dir or Path.cwd()).resolve()
        if env is None:
            if load_file and load_dotenv is not None:
                load_dotenv(root / ".env", override=False)
            source: Mapping[str, str] = os.environ
        else:
            source = env

        seed_audio_model = _text(source, "SEED_AUDIO_MODEL", FIXED_SEED_AUDIO_MODEL)
        if seed_audio_model != FIXED_SEED_AUDIO_MODEL:
            raise ConfigurationError(
                f"SEED_AUDIO_MODEL is fixed to {FIXED_SEED_AUDIO_MODEL}"
            )

        config = cls(
            ark_api_key=_text(source, "ARK_API_KEY"),
            ark_base_url=_text(
                source,
                "ARK_BASE_URL",
                "https://ark.cn-beijing.volces.com/api/v3",
            ).rstrip("/"),
            doubao_model=_text(
                source,
                "DOUBAO_MODEL",
                "doubao-seed-2-0-lite-260215",
            ),
            seedance_model_id=_text(source, "SEEDANCE_MODEL_ID"),
            seedance_max_duration=_int(source, "SEEDANCE_MAX_DURATION", SEEDANCE_MAX_DURATION),
            seedance_task_timeout=_int(source, "SEEDANCE_TASK_TIMEOUT", SEEDANCE_TASK_TIMEOUT),
            mediakit_api_key=_text(source, "MEDIAKIT_API_KEY"),
            seed_audio_api_key=_text(source, "SEED_AUDIO_API_KEY"),
            seed_audio_endpoint=_text(
                source,
                "SEED_AUDIO_ENDPOINT",
                "https://openspeech.bytedance.com/api/v3/tts/create",
            ).rstrip("/"),
            seed_audio_model=seed_audio_model,
            uguu_upload_url=_text(
                source,
                "UGUU_UPLOAD_URL",
                "https://uguu.se/upload",
            ),
            uguu_max_file_mib=_int(source, "UGUU_MAX_FILE_MIB", 128),
            uguu_expire_hours=_int(source, "UGUU_EXPIRE_HOURS", 3),
            http_timeout=_float(source, "HTTP_TIMEOUT", 180.0),
            poll_interval=_float(source, "POLL_INTERVAL", 10.0),
            max_retries=_int(source, "MAX_RETRIES", 3),
            work_dir=_path_from_env(source, "WORK_DIR", Path("work"), root),
            ffmpeg_bin=_tool_from_env(
                source,
                "FFMPEG_BIN",
                "ffmpeg",
                root,
                "tools/ffmpeg/bin/ffmpeg.exe",
            ),
            ffprobe_bin=_tool_from_env(
                source,
                "FFPROBE_BIN",
                "ffprobe",
                root,
                "tools/ffmpeg/bin/ffprobe.exe",
            ),
            mediakit_cli_bin=_tool_from_env(
                source,
                "MEDIAKIT_CLI_BIN",
                "mediakit-cli",
                root,
                "tools/mediakit/mediakit-cli.exe",
            ),
        )
        config.validate_values()
        return config

    def validate_values(self) -> None:
        if not self.ark_base_url.startswith(("http://", "https://")):
            raise ConfigurationError("ARK_BASE_URL must be an HTTP(S) URL")
        if not self.seed_audio_endpoint.startswith(("http://", "https://")):
            raise ConfigurationError("SEED_AUDIO_ENDPOINT must be an HTTP(S) URL")
        if not self.uguu_upload_url.startswith(("http://", "https://")):
            raise ConfigurationError("UGUU_UPLOAD_URL must be an HTTP(S) URL")
        if self.seedance_max_duration <= 0:
            raise ConfigurationError("SEEDANCE_MAX_DURATION must be positive")
        if self.seedance_task_timeout <= 0:
            raise ConfigurationError("SEEDANCE_TASK_TIMEOUT must be positive")
        if self.uguu_max_file_mib <= 0:
            raise ConfigurationError("UGUU_MAX_FILE_MIB must be positive")
        if self.http_timeout <= 0 or self.poll_interval < 0:
            raise ConfigurationError("HTTP_TIMEOUT must be positive and POLL_INTERVAL non-negative")
        if self.max_retries <= 0:
            raise ConfigurationError("MAX_RETRIES must be positive")

    def with_overrides(self, **values: object) -> "AppConfig":
        """Return a copy for GUI-entered values without mutating process env."""

        allowed = set(self.__dataclass_fields__)
        unknown = set(values) - allowed
        if unknown:
            raise ConfigurationError(f"Unknown configuration fields: {sorted(unknown)}")
        updated = replace(self, **values)
        updated.validate_values()
        return updated

    def missing_runtime_values(self) -> list[str]:
        missing: list[str] = []
        for name, value in (
            ("ARK_API_KEY", self.ark_api_key),
            ("MEDIAKIT_API_KEY", self.mediakit_api_key),
            ("SEED_AUDIO_API_KEY", self.seed_audio_api_key),
            ("SEEDANCE_MODEL_ID", self.seedance_model_id),
        ):
            if not value:
                missing.append(name)
        return missing
